version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: hakaton_db-postgres-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357
      POSTGRES_DB: hakaton_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hakaton_network

volumes:
  postgres_data:

networks:
  hakaton_network:
    driver: bridge
