version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: hakaton_db-postgres-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357
      POSTGRES_DB: hakaton_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/backups
    networks:
      - hakaton_network

  backup-on-deploy:
    restart: always
    image: postgres:latest
    container_name: hakaton_db-backup-on-deploy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357
      POSTGRES_DB: hakaton_db
    volumes:
      - backups:/backups
    depends_on:
      - postgres-db
    networks:
      - hakaton_network
    entrypoint: >
      /bin/bash -c "
        # Ожидаем, пока PostgreSQL станет доступен (максимум 60 секунд)
        for i in {1..60}; do
          if pg_isready -h postgres-db -U $${POSTGRES_USER}; then
            echo 'PostgreSQL is ready';
            # Создаем бэкап
            pg_dump -h postgres-db -U $${POSTGRES_USER} $${POSTGRES_DB} > /backups/backup_predeploy_$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).sql;
            exit 0;
          fi;
          echo 'Waiting for PostgreSQL...';
          sleep 1;
        done;
        echo 'Error: PostgreSQL is not ready after 60 seconds';
        exit 1
      "

volumes:
  postgres_data:
  backups:

networks:
  hakaton_network:
    driver: bridge
