version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: hakaton_db-postgres-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357
      POSTGRES_DB: hakaton_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/backups
    networks:
      - hakaton_network
    entrypoint: >
      /bin/bash -c "
        # Запускаем PostgreSQL в фоновом режиме
        /docker-entrypoint.sh postgres &
        # Ожидаем, пока сервер станет доступен (максимум 30 секунд)
        for i in {1..30}; do
          if pg_isready -h localhost -U $${POSTGRES_USER}; then
            echo 'PostgreSQL is ready';
            # Создаем бэкап
            pg_dump -h localhost -U $${POSTGRES_USER} $${POSTGRES_DB} > /backups/backup_predeploy_$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).sql;
            break;
          fi;
          echo 'Waiting for PostgreSQL...';
          sleep 1;
        done
        # Ожидаем завершения работы PostgreSQL
        wait
      "

volumes:
  postgres_data:
  backups:

networks:
  hakaton_network:
    driver: bridge
